Add ref, source and utm_source as referrer
electerious/Ackee pull request #173
Opened 2020-10-24 13:11 UTC by BetaHuhn

Backend implementation to fix #169

2020-10-24 13:16 UTC, BetaHuhn commented
I am having trouble figuring out how to change the URL scalar to a union in the GraphQL API as I am not ver familiar with this. Also currently the UI displays an error as it expects the referrer id to be a URL not a string,

2020-10-24 18:11 UTC, electerious requested changes
Thanks 👍 Please let me know when the two comments are resolved. I will merge it into a dedicated branch and add the GraphQL part tomorrow so you can continue with ackee-track if you want.

2020-10-24 18:11 UTC, electerious commented on src/aggregations/aggregateNewFields.js
> +			(aggregation[0].$match['$or'] = aggregation[0].$match['$or'] || []).push({ [property]: { $ne: null } })
Smart one, but I had to read it a few times to understand what's going on 😃 Let's split it into two lines.

```js
const osProp = 
aggregation[0].$match['$or'] = aggregation[0].$match['$or'] || []
aggregation[0].$match['$or'].push({ [property]: { $ne: null } })
```

or (but I don't know if that's easier to read)

```js
aggregation[0].$match['$or'] = [...(aggregation[0].$match['$or'] || []), { [property]: { $ne: null } }]
```

2020-10-24 18:11 UTC, electerious commented on src/types/records.js
> +		siteReferrer: String
Please revert this file. I will give unions a try :)

2020-10-25 13:00 UTC, electerious approved these changes

2020-10-25 13:00 UTC, merged

2020-10-25 13:12 UTC, electerious commented
Resolved the issues. The union idea didn't work out. I've adjusted the GraphQL schema to return a String for the referrer id. It now needs a isUrl function in the UI to detect URLs (the currently list only works with URLs).

2020-10-25 14:00 UTC, BetaHuhn commented
[electerious/ackee-tracker#27](https://github.com/electerious/ackee-tracker/pull/27) adds support for this feature to the tracker.